# Generated by Django 3.0.8 on 2020-08-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.TextField(blank=True, max_length=100, null=True)),
                ('fulfillment_status', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_status', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shopName', models.TextField(blank=True, max_length=100, null=True)),
                ('apiKey', models.TextField(blank=True, max_length=100, null=True)),
                ('apiPassword', models.TextField(blank=True, max_length=100, null=True)),
                ('shopUrl', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
